<#
    make-test-wsz.ps1 - build a synthetic classic skin for testing the .wsz
    importer (#107, D102).

      powershell -NoProfile -ExecutionPolicy Bypass -File tools\make-test-wsz.ps1

    No skin from the internet is ever committed here, and none needs to be
    downloaded to test the importer: this writes BMPs at the classic sizes
    with a grid and a label on every sprite, so a rectangle taken from the
    wrong place is obvious on screen rather than subtle. The zip it packs is
    a real .wsz as far as the importer is concerned.

    Writes into .sid/ (gitignored, never referenced by code).

    Windows PowerShell 5.1, System.Drawing only.
#>
param(
    [string]$Out = ".sid",
    [string]$Name = "test-skin"
)
$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)
Add-Type -AssemblyName System.Drawing

# The sheets a classic skin is made of, at the sizes the sprite table needs.
$sheets = @{
    "MAIN.BMP"     = @(275, 116)
    "TITLEBAR.BMP" = @(344, 87)
    "CBUTTONS.BMP" = @(136, 36)
    "POSBAR.BMP"   = @(307, 10)
    "VOLUME.BMP"   = @(68, 433)
    "PLAYPAUS.BMP" = @(48, 9)
    "SHUFREP.BMP"  = @(92, 85)
    "TEXT.BMP"     = @(155, 18)
    "NUMBERS.BMP"  = @(108, 13)
    "EQMAIN.BMP"   = @(275, 315)
    "PLEDIT.BMP"   = @(280, 186)
}

# One hue per sheet, so a sprite drawn from the wrong file is obvious.
$hues = @{
    "MAIN.BMP" = 210; "TITLEBAR.BMP" = 30; "CBUTTONS.BMP" = 120; "POSBAR.BMP" = 280
    "VOLUME.BMP" = 60; "PLAYPAUS.BMP" = 0; "SHUFREP.BMP" = 160; "TEXT.BMP" = 300
    "NUMBERS.BMP" = 90; "EQMAIN.BMP" = 190; "PLEDIT.BMP" = 330
}

function Hue-Color([int]$h, [double]$v) {
    $c = $v; $x = $c * (1 - [Math]::Abs((($h / 60.0) % 2) - 1))
    $r = 0.0; $g = 0.0; $b = 0.0
    switch ([int][Math]::Floor($h / 60) % 6) {
        0 { $r = $c; $g = $x }
        1 { $r = $x; $g = $c }
        2 { $g = $c; $b = $x }
        3 { $g = $x; $b = $c }
        4 { $r = $x; $b = $c }
        5 { $r = $c; $b = $x }
    }
    [System.Drawing.Color]::FromArgb([int]($r * 255), [int]($g * 255), [int]($b * 255))
}

$dir = Join-Path $Out $Name
New-Item -ItemType Directory -Force -Path $dir | Out-Null

foreach ($file in $sheets.Keys) {
    $w = $sheets[$file][0]; $h = $sheets[$file][1]; $hue = $hues[$file]
    $bmp = New-Object System.Drawing.Bitmap $w, $h
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    try {
        $g.Clear((Hue-Color $hue 0.18))
        # A grid every 10 px, so an offset that is out by a few shows up.
        $pen = New-Object System.Drawing.Pen ((Hue-Color $hue 0.32)), 1
        for ($x = 0; $x -lt $w; $x += 10) { $g.DrawLine($pen, $x, 0, $x, $h) }
        for ($y = 0; $y -lt $h; $y += 10) { $g.DrawLine($pen, 0, $y, $w, $y) }
        $pen.Dispose()
        # A bright edge, so a sprite's own boundary is visible.
        $edge = New-Object System.Drawing.Pen ((Hue-Color $hue 0.8)), 1
        $g.DrawRectangle($edge, 0, 0, $w - 1, $h - 1)
        $edge.Dispose()
        # The file's name, small, in the top left.
        $font = New-Object System.Drawing.Font "Consolas", 6
        $brush = New-Object System.Drawing.SolidBrush ((Hue-Color $hue 1.0))
        $g.DrawString($file.Replace(".BMP", ""), $font, $brush, 1, 1)
        $font.Dispose(); $brush.Dispose()
    } finally { $g.Dispose() }
    $bmp.Save((Join-Path $dir $file), [System.Drawing.Imaging.ImageFormat]::Bmp)
    $bmp.Dispose()
    "$file  $w x $h"
}

# The two text files. Colours a person would notice if they leaked into the
# wrong place: the rows green on black, the playing row white, the ramp a
# straight blue-to-red climb.
@(
    "[Text]"
    "Normal=#00FF66"
    "Current=#FFFFFF"
    "NormalBG=#101018"
    "SelectedBG=#3355FF"
    "mbFG=#00FF66"
    "mbBG=#101018"
) | Set-Content -Path (Join-Path $dir "PLEDIT.TXT") -Encoding ASCII

$viscolor = foreach ($i in 0..23) {
    $r = [int](255 * $i / 23.0); $b = 255 - $r
    "$r,40,$b // step $i"
}
$viscolor | Set-Content -Path (Join-Path $dir "VISCOLOR.TXT") -Encoding ASCII

# And a readme, which the importer must ignore.
"a synthetic skin, generated by tools/make-test-wsz.ps1" |
    Set-Content -Path (Join-Path $dir "README.NFO") -Encoding ASCII

$zip = Join-Path $Out "$Name.wsz"
if (Test-Path $zip) { Remove-Item $zip }
# .wsz is a zip; Compress-Archive writes one, and the extension is the skin's.
$tmp = Join-Path $Out "$Name.zip"
if (Test-Path $tmp) { Remove-Item $tmp }
Compress-Archive -Path (Join-Path $dir "*") -DestinationPath $tmp
Move-Item $tmp $zip
"$zip  $((Get-Item $zip).Length) bytes"
